[package]
name = "crsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = { version = "0.9.1", features = ["text"] }
coolor = "0.5.1"
